### ISSUE TITLE
[Observability]add metrics for ignored traces 

### ISSUE THREAD

**Issue by JaredTan95** [openinsight-proj/OpenInsight#4]
If `service.name` doesn't exist, we wil skip processing this trace now, but it will confuse users.
https://github.com/openinsight-proj/OpenInsight/blob/main/processor/servicegraphprocessor/processor.go#L184

we can add a `couter` metrics like https://github.com/openinsight-proj/OpenInsight/blob/main/processor/servicegraphprocessor/metrics.go#L24 to alynasis.

**Comment by Frapschen** [comment]
looks cool, can we named it `skipped_spans`?

**Comment by JaredTan95** [comment]
> looks cool, can we named it `skipped_spans`?

make sense.
